#! /bin/sh
# Do not edit this file!
# this file is generated by 'generate_test.pl'.

#
# Maaping test.
# TR #46 mappings.
#
#             api: decodename
#  local_encoding: U-escape
#            conf: language ja
#            conf: language-local ja @LOCALMAP_FILE1@
#            conf: delimiters 3002
#            conf: map nfc delimitermap tr46-map tr46-check language-local nfc
#       localmap1: 309B; 3099
#       localmap2: 309C; 309A
#            from: \u{c0}\u{ff8a}\u{ff9f}\u{ff9d}\u{ff80}\u{ff9e}\u{3002}jp
#         actions: IDN_UNICODECONV IDN_MAP IDN_LOCALCONV
#          result: success
#              to: \u{e0}\u{30d1}\u{30f3}\u{30c0}.jp

################## setup ##################

unset LC_ALL
unset LC_CTYPE
unset LC_MESSAGES
unset LANG
unset IDN_LOCAL_CODESET
unset IDN_LOG_LEVEL

SRCDIR=`dirname $0`
SYSCONFDIR=${SYSCONFDIR-"/etc"}
IGNORE=false
export IDN_LOCAL_CODESET; IDN_LOCAL_CODESET=U-escape

rm -f idn2.conf
touch idn2.conf
echo 'language ja' >> idn2.conf
echo 'language-local ja localmap1' >> idn2.conf
echo 'delimiters 3002' >> idn2.conf
echo 'map nfc delimitermap tr46-map tr46-check language-local nfc' >> idn2.conf

rm -f localmap1
echo '309B; 3099' >> localmap1

rm -f localmap2
echo '309C; 309A' >> localmap2

rm -f localmap3
rm -f localmap4
rm -f localset
rm -f expect.txt
rm -f output.txt

################## test ##################

echo 'from: \u{c0}\u{ff8a}\u{ff9f}\u{ff9d}\u{ff80}\u{ff9e}\u{3002}jp' >> expect.txt
echo 'result: success' >> expect.txt
echo 'to: \u{e0}\u{30d1}\u{30f3}\u{30c0}.jp' >> expect.txt
../common/test_decodename -conffile=idn2.conf -localcheckfile=  -unicodeconv -map -localconv -- '\u{c0}\u{ff8a}\u{ff9f}\u{ff9d}\u{ff80}\u{ff9e}\u{3002}jp' > output.txt

################## teardown ##################

cmp expect.txt output.txt > /dev/null 2>&1
RESULT=$?
[ X$IGNORE = Xtrue ] && RESULT=77
if [ X$QUIET != Xtrue ]; then
    if [ $RESULT -eq 0 ]; then
        echo "PASS: $0"
    elif [ $RESULT -eq 77 ]; then
        echo "SKIP: $0"
    else
        echo "FAIL: $0"
    fi
fi
[ $RESULT -eq 0 -o $RESULT -eq 77 ] || exit $RESULT
rm -f idn2.conf
rm -f localmap1
rm -f localmap2
rm -f localmap3
rm -f localmap4
rm -f localset
rm -f expect.txt
rm -f output.txt
exit $RESULT
