/*
 * Do not edit this file!
 * This file is generated from:
 *    DerivedCoreProperties.txt (version 6.3.0)
 */

#ifndef IDN_CASEIGNORABLE_H
#define IDN_CASEIGNORABLE_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>

/*
 * Table accessor.
 */
extern int
idn__sparsemap_getcaseignorable(unsigned long v);

#ifdef __cplusplus
}
#endif

#endif
