/*
 * Do not edit this file!
 * This file is generated from:
 *    UnicodeData.txt (version 6.3.0)
 */

#ifndef IDN_COMBININGCHARACTER_H
#define IDN_COMBININGCHARACTER_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>

/*
 * Table accessor.
 */
extern int
idn__sparsemap_getcombiningcharacter(unsigned long v);

#ifdef __cplusplus
}
#endif

#endif
