/*
 * Do not edit this file!
 * This file is generated from:
 *    UnicodeData.txt (version 6.3.0)
 *    DerivedCoreProperties.txt (version 6.3.0)
 */

#ifndef IDN_COMBININGCLASS_H
#define IDN_COMBININGCLASS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>

/*
 * Table accessor.
 */
extern unsigned char
idn__sparsemap_getcombiningclass(unsigned long v);

#ifdef __cplusplus
}
#endif

#endif
