/*
 * Do not edit this file!
 * This file is generated from:
 *    UnicodeData.txt (version 6.3.0)
 *    CompositionExclusions.txt (version 6.3.0)
 */

#ifndef IDN_COMPOSITION_H
#define IDN_COMPOSITION_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>

#define NUM_COMPOSITIONS(v)     ((v) >> 16)

/*
 * composition_seq table structure.
 */
struct composition {
	unsigned long c2;    /* 2nd character */
	unsigned long comp;  /* composed character */
};

/*
 * Table accessor.
 */
extern unsigned long
idn__sparsemap_getcomposition(unsigned long v);
const struct composition *
idn__sparsemap_getcompositionseq(unsigned long idx);

#ifdef __cplusplus
}
#endif

#endif
