/*
 * Do not edit this file!
 * This file is generated from:
 *    idna-tables.xml (version rfc6452 (2011-11-14))
 */

#ifndef IDN_IDNACATEGORY_H
#define IDN_IDNACATEGORY_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>

/*
 * IDNA code point categories.
 */
typedef enum {
	idn__idnacategory_pvalid     =  0,
	idn__idnacategory_contextj   =  1,
	idn__idnacategory_contexto   =  2,
	idn__idnacategory_disallowed =  3,
	idn__idnacategory_unassigned =  4,
	idn__idnacategory_unknown = -1
} idn__idnacategory_t;

/*
 * Table accessor.
 */
extern idn__idnacategory_t
idn__sparsemap_getidnacategory(unsigned long v);

#ifdef __cplusplus
}
#endif

#endif
