/*
 * Do not edit this file!
 * This file is generated automatically.
 */

#ifndef IDN_IDNAVERSION_H
#define IDN_IDNAVERSION_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>

#define IDNKIT_VERSION_IDNATABLE "rfc6452 (2011-11-14)"

#ifdef __cplusplus
}
#endif

#endif
