/*
 * Do not edit this file!
 * This file is generated from:
 *    iso639.txt (version <unknown>)
 */

#ifndef IDN_ISO639LANG_H
#define IDN_ISO639LANG_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>

/*
 * Static lanuage name aliases.
 */
typedef struct {
	char *alias_name;
	char *real_name;
} idn__iso639lang_t;

extern const idn__iso639lang_t iso639langs[];


#ifdef __cplusplus
}
#endif

#endif
