/*
 * Do not edit this file!
 * This file is generated from:
 *    UnicodeData.txt (version 6.3.0)
 *    ArabicShaping.txt (version 6.3.0)
 */

#ifndef IDN_JOININGTYPE_H
#define IDN_JOININGTYPE_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>

/*
 * Joining types.
 */
typedef enum {
	idn__joiningtype_U = 0,
	idn__joiningtype_R = 1,
	idn__joiningtype_L = 2,
	idn__joiningtype_D = 3,
	idn__joiningtype_C = 4,
	idn__joiningtype_T = 5,
	idn__joiningtype_unknown = -1
} idn__joiningtype_t;

/*
 * Table accessor.
 */
extern idn__joiningtype_t
idn__sparsemap_getjoiningtype(unsigned long v);

#ifdef __cplusplus
}
#endif

#endif
