/*
 * Do not edit this file!
 * This file is generated from:
 *    Scripts.txt (version 6.3.0)
 */

#ifndef IDN_SCRIPT_H
#define IDN_SCRIPT_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>

/*
 * Script names.
 */
typedef enum {
	idn__script_common = 1, 
	idn__script_latin = 2, 
	idn__script_greek = 3, 
	idn__script_cyrillic = 4, 
	idn__script_armenian = 5, 
	idn__script_hebrew = 6, 
	idn__script_arabic = 7, 
	idn__script_syriac = 8, 
	idn__script_thaana = 9, 
	idn__script_devanagari = 10, 
	idn__script_bengali = 11, 
	idn__script_gurmukhi = 12, 
	idn__script_gujarati = 13, 
	idn__script_oriya = 14, 
	idn__script_tamil = 15, 
	idn__script_telugu = 16, 
	idn__script_kannada = 17, 
	idn__script_malayalam = 18, 
	idn__script_sinhala = 19, 
	idn__script_thai = 20, 
	idn__script_lao = 21, 
	idn__script_tibetan = 22, 
	idn__script_myanmar = 23, 
	idn__script_georgian = 24, 
	idn__script_hangul = 25, 
	idn__script_ethiopic = 26, 
	idn__script_cherokee = 27, 
	idn__script_canadian_aboriginal = 28, 
	idn__script_ogham = 29, 
	idn__script_runic = 30, 
	idn__script_khmer = 31, 
	idn__script_mongolian = 32, 
	idn__script_hiragana = 33, 
	idn__script_katakana = 34, 
	idn__script_bopomofo = 35, 
	idn__script_han = 36, 
	idn__script_yi = 37, 
	idn__script_old_italic = 38, 
	idn__script_gothic = 39, 
	idn__script_deseret = 40, 
	idn__script_inherited = 41, 
	idn__script_tagalog = 42, 
	idn__script_hanunoo = 43, 
	idn__script_buhid = 44, 
	idn__script_tagbanwa = 45, 
	idn__script_limbu = 46, 
	idn__script_tai_le = 47, 
	idn__script_linear_b = 48, 
	idn__script_ugaritic = 49, 
	idn__script_shavian = 50, 
	idn__script_osmanya = 51, 
	idn__script_cypriot = 52, 
	idn__script_braille = 53, 
	idn__script_buginese = 54, 
	idn__script_coptic = 55, 
	idn__script_new_tai_lue = 56, 
	idn__script_glagolitic = 57, 
	idn__script_tifinagh = 58, 
	idn__script_syloti_nagri = 59, 
	idn__script_old_persian = 60, 
	idn__script_kharoshthi = 61, 
	idn__script_balinese = 62, 
	idn__script_cuneiform = 63, 
	idn__script_phoenician = 64, 
	idn__script_phags_pa = 65, 
	idn__script_nko = 66, 
	idn__script_sundanese = 67, 
	idn__script_lepcha = 68, 
	idn__script_ol_chiki = 69, 
	idn__script_vai = 70, 
	idn__script_saurashtra = 71, 
	idn__script_kayah_li = 72, 
	idn__script_rejang = 73, 
	idn__script_lycian = 74, 
	idn__script_carian = 75, 
	idn__script_lydian = 76, 
	idn__script_cham = 77, 
	idn__script_tai_tham = 78, 
	idn__script_tai_viet = 79, 
	idn__script_avestan = 80, 
	idn__script_egyptian_hieroglyphs = 81, 
	idn__script_samaritan = 82, 
	idn__script_lisu = 83, 
	idn__script_bamum = 84, 
	idn__script_javanese = 85, 
	idn__script_meetei_mayek = 86, 
	idn__script_imperial_aramaic = 87, 
	idn__script_old_south_arabian = 88, 
	idn__script_inscriptional_parthian = 89, 
	idn__script_inscriptional_pahlavi = 90, 
	idn__script_old_turkic = 91, 
	idn__script_kaithi = 92, 
	idn__script_batak = 93, 
	idn__script_brahmi = 94, 
	idn__script_mandaic = 95, 
	idn__script_chakma = 96, 
	idn__script_meroitic_cursive = 97, 
	idn__script_meroitic_hieroglyphs = 98, 
	idn__script_miao = 99, 
	idn__script_sharada = 100, 
	idn__script_sora_sompeng = 101, 
	idn__script_takri = 102, 
	idn__script_unknown = -1
} idn__script_t;

/*
 * Table accessor.
 */
extern idn__script_t
idn__sparsemap_getscript(unsigned long v);

#ifdef __cplusplus
}
#endif

#endif
