/*
 * Do not edit this file!
 * This file is generated from:
 *    IdnaMappingTable.txt (version 6.3.0)
 */

#ifndef IDN_TR46CASEFOLD_H
#define IDN_TR46CASEFOLD_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>

#define IS_TR46CASEFOLD_DEVIATION(v) ((v) & 0x8000UL)
#define IS_TR46CASEFOLDSEQ_DATA_END(v) ((v) & 0x80000000UL)
#define TR46CASEFOLDSEQ_DATA(v) ((v) & ~0x80000000UL)

/*
 * Table accessor.
 */
extern unsigned long
idn__sparsemap_gettr46casefold(unsigned long v);
extern const unsigned long *
idn__sparsemap_gettr46casefoldseq(unsigned long idx);

#ifdef __cplusplus
}
#endif

#endif
