/*
 * Do not edit this file!
 * This file is generated from:
 *    IdnaMappingTable.txt (version 6.3.0)
 */

#ifndef IDN_TR46CATEGORY_H
#define IDN_TR46CATEGORY_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>

/*
 * TR46 codepoint categories.
 */
typedef enum {
	idn__tr46category_valid      =  0,
	idn__tr46category_disallowed_std3_mapped =  1,
	idn__tr46category_disallowed_std3_valid =  1,
	idn__tr46category_disallowed =  1,
	idn__tr46category_mapped     =  2,
	idn__tr46category_ignored    =  3,
	idn__tr46category_deviation  =  4,
	idn__tr46category_unknown = -1
} idn__tr46category_t;

/*
 * Table accessor.
 */
extern idn__tr46category_t
idn__sparsemap_gettr46category(unsigned long v);

#ifdef __cplusplus
}
#endif

#endif
