/*
 * Do not edit this file!
 * This file is generated automatically.
 */

#ifndef IDN_UNICODEVERSION_H
#define IDN_UNICODEVERSION_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>

#define IDNKIT_VERSION_UNICODE "6.3.0"

#ifdef __cplusplus
}
#endif

#endif
