/*
 * Do not edit this file!
 * This file is generated from:
 *    UnicodeData.txt (version 6.3.0)
 */

#ifndef IDN_WIDTH_H
#define IDN_WIDTH_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>

/*
 * Table accessor.
 */
extern unsigned long
idn__sparsemap_getwidth(unsigned long v);

#ifdef __cplusplus
}
#endif

#endif
