#! /bin/sh
# Do not edit this file!
# this file is generated by 'generate_test.pl'.

#
# ZERO WIDTH NON-JOINER context rule test.
# The input name is U+0628 U+00AD... U+200C U+00AD... U+062F
# (Joining_Type:T... + U+200C + Joining_Type:T... + Joining_Type:R).
#
#             api: encodename
#  local_encoding: U-escape
#            conf: 
#            from: \u{628}\u{ad}\u{ad}\u{ad}\u{200c}\u{ad}\u{ad}\u{ad}\u{62f}
#         actions: IDN_UNICODECONV IDN_CTXJCHECK IDN_LOCALCONV
#          result: success
#              to: \u{628}\u{ad}\u{ad}\u{ad}\u{200c}\u{ad}\u{ad}\u{ad}\u{62f}

################## setup ##################

unset LC_ALL
unset LC_CTYPE
unset LC_MESSAGES
unset LANG
unset IDN_LOCAL_CODESET
unset IDN_LOG_LEVEL

SRCDIR=`dirname $0`
SYSCONFDIR=${SYSCONFDIR-"/etc"}
IGNORE=false
export IDN_LOCAL_CODESET; IDN_LOCAL_CODESET=U-escape

rm -f idn2.conf
touch idn2.conf
echo '' >> idn2.conf

rm -f localmap1
rm -f localmap2
rm -f localmap3
rm -f localmap4
rm -f localset
rm -f expect.txt
rm -f output.txt

################## test ##################

echo 'from: \u{628}\u{ad}\u{ad}\u{ad}\u{200c}\u{ad}\u{ad}\u{ad}\u{62f}' >> expect.txt
echo 'result: success' >> expect.txt
echo 'to: \u{628}\u{ad}\u{ad}\u{ad}\u{200c}\u{ad}\u{ad}\u{ad}\u{62f}' >> expect.txt
../common/test_encodename -conffile=idn2.conf -localcheckfile=  -unicodeconv -ctxjcheck -localconv -- '\u{628}\u{ad}\u{ad}\u{ad}\u{200c}\u{ad}\u{ad}\u{ad}\u{62f}' > output.txt

################## teardown ##################

cmp expect.txt output.txt > /dev/null 2>&1
RESULT=$?
[ X$IGNORE = Xtrue ] && RESULT=77
if [ X$QUIET != Xtrue ]; then
    if [ $RESULT -eq 0 ]; then
        echo "PASS: $0"
    elif [ $RESULT -eq 77 ]; then
        echo "SKIP: $0"
    else
        echo "FAIL: $0"
    fi
fi
[ $RESULT -eq 0 -o $RESULT -eq 77 ] || exit $RESULT
rm -f idn2.conf
rm -f localmap1
rm -f localmap2
rm -f localmap3
rm -f localmap4
rm -f localset
rm -f expect.txt
rm -f output.txt
exit $RESULT
